<a href="https://colab.research.google.com/github/Kylie-WBS/Kylie-WBS-DataScience-GenAI-Submissions/blob/main/Exercise%202_01_data_and_feature_engineering_in_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://drive.google.com/uc?export=view&id=1xqQczl0FG-qtNA2_WQYuWePW9oU8irqJ)

# Data and Feature Engineering
This Notebook will introduce us to preparing our datasets for data science and AI workloads. For sturctured data, this will often utilise popular Python libraries such as Pandas, which will be the focus for this Notebook.

### What is Pandas?
As Python has grown to become a popular solution for data analysis, many new tools have been introduced to support such tasks. Pandas is arguably the most popular and widely used of these, although it does have some limitations (if working with very large datasets you may want to look at Dask and/or PySpark).

First, we will import it into our session. This effectively means we have opened the library in the background, and can now use the [functions](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_10_functions.ipynb) built into it. We will also import numpy - another widely used Python package for working with numerical data (the name is a portmanteau of "numerical" and "python"). By convention we import pandas as "pd" and numpy as "np". This is equivalent to giving it a variable name.

In [ ]:
import pandas as pd
import numpy as np

### Testing our installation
To test everything is working we will create some fake data frame using numpy and load it into a pandas dataframe (more on these below). First we will create the random numbers:

In [ ]:
x = np.random.rand(10,1)
x

array([[0.19358833],
       [0.17503344],
       [0.85220208],
       [0.32454187],
       [0.92817678],
       [0.58990681],
       [0.88621071],
       [0.32770407],
       [0.46913519],
       [0.92799261]])

The commands here have told numpy to create a set of random numbers between zero and one. The arguments we have passed, "1" and "10", tells numpy we want a 10x1 array of numbers (i.e. a table (more accurately a vector) with 10 rows and 1 column).

Next we will create a pandas dataframe using "x":

In [ ]:
testdf = pd.DataFrame(x)
testdf

          0
0  0.193588
1  0.175033
2  0.852202
3  0.324542
4  0.928177
5  0.589907
6  0.886211
7  0.327704
8  0.469135
9  0.927993

We have now successfully created a pandas dataframe!

### What are Dataframes?
Pandas has a very elegant way of managing data, very much borrowed from the statistical language R, mostly based around dataframes. You can think of dataframes a bit like an Excel table with rows, columns and common operations like sum, average and so on. We can use this on top of our previous work on lists and dictionaries (etc.) more usable and malleable.

To begin with we will create a dataset - in this case a [dictionary](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_05_dictionaries.ipynb).

In [ ]:
orders = {'o10001':{'date':'2024/01/10', 'product':'Hoodie', 'quantity':'1'},
            'o10002':{'date':'2024/01/13', 'product':'Tote bag', 'quantity':'2'},
            'o10003':{'date':'2024/01/14', 'product':'Pencil', 'quantity':'10'},
            'o10004':{'date':'2024/01/15', 'product':'T-shirt', 'quantity':'2'}
}
orders

{'o10001': {'date': '2024/01/10', 'product': 'Hoodie', 'quantity': '1'},
 'o10002': {'date': '2024/01/13', 'product': 'Tote bag', 'quantity': '2'},
 'o10003': {'date': '2024/01/14', 'product': 'Pencil', 'quantity': '10'},
 'o10004': {'date': '2024/01/15', 'product': 'T-shirt', 'quantity': '2'}}

We can convert this to a Dataframe with great ease

In [ ]:
import pandas as pd
import numpy as np

orders_df = pd.DataFrame(orders)
orders_df

              o10001      o10002      o10003      o10004
date      2024/01/10  2024/01/13  2024/01/14  2024/01/15
product       Hoodie    Tote bag      Pencil     T-shirt
quantity           1           2          10           2

We can even create such outputs from more complex dictionaries, such as a dictionary which includes a nested list:

In [ ]:
customers = {'Mark':{'name':'Mark Johnson', 'open_orders':3, 'orders':['o10001', 'o10002', 'o10004']},
             'Katy':{'name':'Katy Hoad', 'open_orders':0, 'orders':[]},
             'Angela':{'name':'Angela Lorenz', 'open_orders':1, 'orders':['o10003']},
             'Bo':{'name':'Bo Kelestyn', 'open_orders':0, 'orders':[]}
}
customers

{'Mark': {'name': 'Mark Johnson',
  'open_orders': 3,
  'orders': ['o10001', 'o10002', 'o10004']},
 'Katy': {'name': 'Katy Hoad', 'open_orders': 0, 'orders': []},
 'Angela': {'name': 'Angela Lorenz', 'open_orders': 1, 'orders': ['o10003']},
 'Bo': {'name': 'Bo Kelestyn', 'open_orders': 0, 'orders': []}}

In [ ]:
customers_df = pd.DataFrame(customers)
customers_df

                                 Mark       Katy         Angela           Bo
name                     Mark Johnson  Katy Hoad  Angela Lorenz  Bo Kelestyn
open_orders                         3          0              1            0
orders       [o10001, o10002, o10004]         []       [o10003]           []

Pandas dataframes can also be built from various other data structures and sources (including Excel files, CSVs, text files, databases and many more). For example, we can make our dataframe from a set of [lists](https://github.com/MJMortensonWarwick/IB2AD0_Data_Science_GenerativeAI/blob/main/1_04_lists.ipynb):

In [ ]:
a = [1, 2, 3, 4]
b = ["a", "b", "c", "d"]
c = [True, False, True, False]

listdf = pd.DataFrame([a, b, c])
listdf

      0      1     2      3
0     1      2     3      4
1     a      b     c      d
2  True  False  True  False

### EXERCISE
Try building you own dataframes from a list and/or dictionary you create. What would happen if you have an item missing from one element. E.g. if "c" in the above example only had three items - True, False, True - rather than four. Test it - does the output match your expectation?

##Exercise
For this exercise I built my own dataset of dog breeds, first as a **dictionary** and then as a set of **lists**. I then tested what happens when one element is missing an item.

### 1. A DataFrame from a dictionary
The following block creates a dictionary where each key is a dog breed, and each value is another dictionary with the breed's country of origin, size and typical lifespan in years.

In [ ]:
Tbreeds = {'Labrador Retriever': {'origin': 'Canada', 'size': 'Large', 'lifespan': 12},
          'Border Collie': {'origin': 'United Kingdom', 'size': 'Medium', 'lifespan': 13},
          'Shiba Inu': {'origin': 'Japan', 'size': 'Small', 'lifespan': 14},
          'French Bulldog': {'origin': 'France', 'size': 'Small', 'lifespan': 11}
}

breeds_df = pd.DataFrame(breeds)
breeds_df

         Labrador Retriever   Border Collie Shiba Inu French Bulldog
origin               Canada  United Kingdom     Japan         France
size                  Large          Medium     Small          Small
lifespan                 12              13        14             11

The outer keys (the breed names) became the **columns**. It's easier to read with one breed per row, so the next block flips the table using `.T` ("transpose").

In [ ]:
breeds_df.T

                            origin    size lifespan
Labrador Retriever          Canada   Large       12
Border Collie       United Kingdom  Medium       13
Shiba Inu                    Japan   Small       14
French Bulldog              France   Small       11

### 2. A DataFrame from lists
The following block builds the same kind of table from three lists. Each list becomes one **row**.

In [ ]:
breed_names = ['Labrador Retriever', 'Border Collie', 'Shiba Inu', 'French Bulldog']
lifespans = [12, 13, 14, 11]
is_small = [False, False, True, True]

breeds_list_df = pd.DataFrame([breed_names, lifespans, is_small])
breeds_list_df

                    0              1          2               3
0  Labrador Retriever  Border Collie  Shiba Inu  French Bulldog
1                  12             13         14              11
2               False          False       True            True

### 3. Testing a missing item
**My prediction:** I ecpect pandas to throw an error because the lists are no longer the same length, or leave a blank where the missing value should be.

**Test A: lists of lists.** Here `is_small` only has three items instead of four.

In [ ]:
is_small_short = [False, False, True]

short_list_df = pd.DataFrame([breed_names, lifespans, is_small_short])
short_list_df

                    0              1          2               3
0  Labrador Retriever  Border Collie  Shiba Inu  French Bulldog
1                  12             13         14              11
2               False          False       True            None

Pandas did not throw an error. It filled the gap in the last row with `None`, which is how Python represents "no value".

**Test B: a dictionary of lists.** This time each list becomes a **column**. I used `try` and `except` so that, if pandas throws an error, the message is printed instead of stopping the notebook.

In [ ]:
try:
    short_dict_df = pd.DataFrame({'breed': breed_names, 'lifespan': lifespans, 'is_small': is_small_short})
    print(short_dict_df)
except ValueError as error:
    print('Error:', error)

Error: All arrays must be of the same length

This time pandas refused and raised an error, because every column must have the same number of rows.

**Test C: a dictionary of dictionaries.** Here the Shiba Inu is missing its "size" entry.

In [ ]:
breeds_missing = {'Labrador Retriever': {'origin': 'Canada', 'size': 'Large'},
                  'Shiba Inu': {'origin': 'Japan'}
}

pd.DataFrame(breeds_missing)

       Labrador Retriever Shiba Inu
origin             Canada     Japan
size                Large       NaN

Pandas matched the values up by their keys and filled the Shiba Inu's missing size with `NaN` ("Not a Number"), pandas' marker for a missing value.

### Conclusion
Whether pandas accepts a missing item depends on how the data is structured:
- **List of lists (each list is a row):** works, and the gap is filled with `None`.
- **Dictionary of lists (each list is a column):** fails with a `ValueError`, as all columns must be the same length.
- **Dictionary of dictionaries:** works, and the gap is filled with `NaN`, because pandas lines values up by their labels.